//////////////////////////////////////////////////////////////////
// Copyright (c) 2016-2017 Contributors to the Eclipse Foundation 
//
// See the NOTICES file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// All rights reserved. This program and the accompanying materials 
// are made available under the terms of the Apache License, Version 2.0
// which accompanies this distribution and is available at
// http://www.opensource.org/licenses/apache2.0.php
//
// SPDX-License-Identifier: Apache-2.0
// 
// Authors: Mark Struberg
//////////////////////////////////////////////////////////////////

[[configexamples]]
== Configuration Usage Examples

An application can access it's configured values via a `Config` instance.
A user can use the `ConfigProvider` to access the `Config` of an application or simply use `@Inject Config` within Depencency-Injection managed components.

=== Simple Programmatic Example

[source, java]
----
public class ConfigUsageSample {

    public void useTheConfig() {
        // get access to the Config instance
        Config config = ConfigProvider.getConfig();

        String serverUrl = config.getValue("acme.myprj.some.url", String.class);
        Integer serverPort = config.getValue("acme.myprj.some.port", Integer.class);

        callToServer(serverUrl, serverPort);
    }
}
----

If you need to access a different server then you can e.g. change the configuration via a `-D` system property:

[source, text]
----
$> java -jar some.jar -Dacme.myprj.some.url=http://other.server/other/endpoint
----

Note that this is only one example how to possibly configure your application.
One can also register <<custom_configsources, Custom ConfigSources>> to e.g. pick up values from a database table, etc.

=== Simple Dependency Injection Example

Microprofile-Config also provides ways to inject configured values into your beans using the `@Inject` and the `@ConfigProperty` qualifier.

[source, java]
----
@ApplicationScoped
public class InjectedConfigUsageSample {

    @Inject
    private Config config;

    @Inject
    @ConfigProperty(name="myprj.some.url")
    private String someUrl;

    @Inject
    @ConfigProperty(name="myprj.some.port")
    private Optional<Integer> somePort;

    @Inject
    @ConfigProperty(name="myprj.some.dynamic.timeout", defaultValue="100")
    private javax.inject.Provider<Long> timeout;
}
----

