//
// Copyright (c) 2016-2017 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Contributors:
// Mark Struberg
// Emily Jiang

[[configexamples]]
== Config Usage Examples


An application can obtain it's configuration programmatically via the `ConfigProvider`.
In CDI enabled beans it can also get injected via `@Inject Config`.
An application can then access its configured values via this `Config` instance.

=== Simple Programmatic Example

[source, java]
----
public class ConfigUsageSample {

    public void useTheConfig() {
        // get access to the Config instance
        Config config = ConfigProvider.getConfig();

        String serverUrl = config.getValue("acme.myprj.some.url", String.class);
        callToServer(serverUrl);

        // or
        ConfigValue configServerUrl = config.getConfigValue("acme.myprj.some.url");
        callToServer(configServerUrl.getValue());
    }
}
----

If you need to access a different server then you can e.g. change the configuration via a Java `-D` system property:

[source, text]
----
$> java -Dacme.myprj.some.url=http://other.server/other/endpoint -jar some.jar
----

Note that this is only one example how to possibly configure your application.
Another example is to register <<custom_configsources, Custom ConfigSources>> to e.g. pick up values from a database table, etc.

If a config value is a comma(`,`) separated string, this value can be automatically converted to a multiple element array with `\` as the escape character.
When specifying the property `myPets=dog,cat,dog\\,cat` in a config source, the following code snippet can be used to obtain an array.
----
 String[] myPets = config.getValue("myPets", String[].class);
 //myPets = {"dog", "cat", "dog,cat"}
----


=== Simple Dependency Injection Example

MicroProfile Config also provides ways to inject configured values into your beans using the `@Inject` and the `@ConfigProperty` qualifier.
The `@Inject` annotation declares an injection point. When using this on a passivation capable bean, refer to https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#passivating_scope[CDI Specification^]
for more details on how to make the injection point to be passivation capable.
[source, java]
----
@ApplicationScoped
public class InjectedConfigUsageSample {

    @Inject
    private Config config;

    //The property myprj.some.url must exist in one of the configsources, otherwise a
    //DeploymentException will be thrown.
    @Inject
    @ConfigProperty(name="myprj.some.url")
    private String someUrl;

    // You can also inject a configuration using the ConfigValue metadata object. The
    // configured value will not lead to a DeploymentException if the value is missing.
    // A default value can also be specified like any other configuration.
    @Inject
    @ConfigProperty(name="myprj.another.url")
    private ConfigValue anotherUrl;

    //The following code injects an Optional value of myprj.some.port property.
    //Contrary to natively injecting the configured value, this will not lead to a
    //DeploymentException if the value is missing.
    @Inject
    @ConfigProperty(name="myprj.some.port")
    private Optional<Integer> somePort;

    // You can also use the specialized Optional classes like OptionalInt,
    // OptionalDouble, or OptionalLong to perform the injection. The configured value
    // will not lead to a DeploymentException if the value is missing.
    @Inject
    @ConfigProperty(name="myprj.some.port")
    private OptionalInt somePort;

    //Injects a Provider for the value of myprj.some.dynamic.timeout property to
    //resolve the property dynamically. Each invocation to Provider#get() will
    //resolve the latest value from underlying Config.
    //The existence of configured values will get checked during startup.
    //Instances of Provider<T> are guaranteed to be Serializable.
    @Inject
    @ConfigProperty(name="myprj.some.dynamic.timeout", defaultValue="100")
    private javax.inject.Provider<Long> timeout;

    //Injects a Supplier for the value of myprj.some.supplier.timeout property to
    //resolve the property dynamically. Each invocation to Supplier#get() will
    //resolve the latest value from underlying Config.
    @Inject
    @ConfigProperty(name="myprj.some.supplier.timeout", defaultValue="100")
    private java.util.function.Supplier<Long> timeout;

    //The following code injects an Array, List or Set for the `myPets` property,
    //where its value is a comma separated value ( myPets=dog,cat,dog\\,cat)
    @Inject @ConfigProperty(name="myPets") private String[] myArrayPets;
    @Inject @ConfigProperty(name="myPets") private List<String> myListPets;
    @Inject @ConfigProperty(name="myPets") private Set<String> mySetPets;
}
----

=== Aggregate related properties into a single POJO Example

When injecting a number of related configuration properties, it can be tedious to repeat the statement of `ConfigProperty` in scatter places. 
Since they are related, it makes more sense to aggregate them into a single property class. 

MicroProfile Config provides a way to look up a number of configuration properties starting with the same prefix using the `@ConfigProperties` annotation, e.g. `ConfigProperties(prefix="myPrefix")`.
When annotating a class with `@ConfigProperties` or `@ConfigProperties(prefix="myPrefix")`, any of its fields, regardless of the visibility, maps to a configuration property via the following mapping rules. 

* If the `prefix` is present, the field `x` maps to the configuration property `<prefix>.x`. 
* If the `prefix` is absent, the field `x` maps to the property name `x`. 

If the field name `x` needs to be different from the config property name `y`, use `@ConfigProperty(name="y")` to perform the transformation. 
If the prefix is present, the field `x` maps to the configuration property `<prefix>.y`, otherwise `y`.

Considering the following config sources:

[source, text]
----
config_ordinal = 120
server.host = localhost
server.port=9080
server.endpoint=query
server.old.location=London
----

[source, text]
----
config_ordinal = 150
client.host = myHost
client.port=9081
client.endpoint=shelf
client.old.location=Dublin
host = anotherHost
port=9082
endpoint=book
old.location=Berlin
----

In order to retrieve the above properties in a single property class, you can use the `@ConfigProperties` annotation with a prefix.

[source, java]
----

@ConfigProperties(prefix="server")
@ApplicationScoped
public class Details {
    public String host; // the value of the configuration property server.host
    public int port;   // the value of the configuration property server.port
    private String endpoint; //the value of the configuration property server.endpoint
    public @ConfigProperty(name="old.location")
    String location; //the value of the configuration property server.old.location 
    public String getEndpoint() {
        return endpoint;      
    }     
}
----

You can then use one of the following to retrieve the properties.

* Directly inject the bean annotated with `@ConfigProperties`
[source, java]
----
@Inject Details serverDetails;
----

The `serverDetails` will contain the following info, as the prefix is `server`:

```
serverDetails.host -> server.host -> localhost
serverDetails.port -> server.port -> 9080
serverDetails.endpoint -> server.endpoint -> query
serverDetails.getLocation() -> server.old.location -> London
```
* Specify `@ConfigProperties` when injecting the bean annotated with `@ConfigProperties`

In this case, the prefix associated with `@ConfigProperties` on this injection point overrides the prefix specified on the bean class.

----
@Inject @ConfigProperties(prefix="client") Details clientDetails;
----
The prefix `client` overrides the prefix `server` on the `ServerDetails` bean. Therefore, this will retrieve the following properties.

```
clientDetails.host -> client.host -> myHost
clientDetails.port -> client.port -> 9081
clientDetails.endpoint -> client.endpoint -> shelf
clientDetails.getLocation() -> client.old.location -> Dublin
```
If `@ConfigProperties` has no associated prefix, it means the prefix is empty. e.g.
----
@Inject @ConfigProperties Details details; //prefix is empty
----
The absence of the prefix means the prefix is empty, which overrides the prefix set on the bean class `server`. Therefore, this will retrieve the following properties.

```
details.host -> host -> anotherHost
details.port -> port -> 9082
details.endpoint -> endpoint -> book
details.getLocation() -> old.location -> Berlin
```

In the above two types of injection lookup, the configuration properties class must contain a zero-arg constructor. Otherwise, DeploymentException will be thrown. 
If any of the property is missing and there is neither default value nor property is not optional, DeploymentException will be thrown. 
In order to avoid this, you can supply a default value when defining the field. Alternatively, you can use `@ConfigProperty` to provide a default value. 
You can also use `Optional<T>` or OptionalInt, OptionalDouble, OptionalLong as the type.
If any of the property value cannot be converted to the specified type, DeploymentException will be thrown as well.

* programmatic look up via `Config.getConfigProperties()`
[source, java]
----
Config config = ConfigProvider.getConfig();
Details serverDetails = config.getConfigProperties(Details.class);
Details clientDetails = config.getConfigProperties(Details.class, "client"); 
Details details = config.getConfigProperties(Details.class, ""); //use no prefix
----

In the above example, the `serverDetails` will contain the following info, because the prefix `server` on the bean class `Details` is in action:

```
serverDetails.host -> server.host -> localhost
serverDetails.port -> server.port -> 9080
serverDetails.endpoint -> server.endpoint -> query
serverDetails.getLocation() -> server.old.location -> London
```
The `clientDetails` will retrieve the following properties, because the specified prefix `client` overrides the prefix on the bean class.

```
clientDetails.host -> client.host -> myHost
clientDetails.port -> client.port -> 9081
clientDetails.endpoint -> client.endpoint -> shelf
clientDetails.getLocation() -> client.old.location -> Dublin
```
The `empty` prefix overrides the prefix set on the bean class `server`. Therefore, this will retrieve the following properties.

```
details.host -> host -> anotherHost
details.port -> port -> 9082
details.endpoint -> endpoint -> book
details.getLocation() -> old.location -> Berlin
```
In the above programmatic lookup, the configuration properties class must contain a zero-arg constructor. Otherwise, `java.lang.IllegalArgumentException` will be thrown. 

If any of the property cannot be found and there is neither default value nor property is not optional, `java.util.NoSuchElementException` will be thrown. 
In order to avoid this, you can supply a default value when defining the field. Alternatively, you can use `@ConfigProperty` to provide a default value. 
You can also use `Optional<T>` or OptionalInt, OptionalDouble, OptionalLong as the type. If any property values cannot be converted to the specified type, `java.lang.IllegalArgumentException` will be thrown.

When using programmatic lookup of the configuration properties, the configuration properties class does not need to be annotated with 
`@ConfigProperties`, if no prefix is to be supplied. The usage of the annotation `ConfigProperties` is only for supplying the prefix. 
However, when using injection of the configuration properties, the configuration properties class, which should be a CDI bean, must be annotated with `@ConfigProperties`. 
Otherwise, the fields will not be automatically resolved to the corresponding configuration properties.


