//
// Copyright (c) 2016, 2017 IBM Corp. and others
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

# Configuration for MicroProfile

## Status

MicroProfile Config proposal!

== Rational

The majority of applications need to be configured based on a running environment.
It must be possible to modify configuration data from outside an application so that the application itself does not need to be repackaged.

The configuration data can come from different locations and in different formats (e.g. system properties, system environment variables, .properties, .xml, datasource).
We call these config locations ConfigSources.
If the same property is defined in multiple ConfigSources, we apply a policy to specify which one of the values will effectively be used.

Under some circumstances, some data sources may change dynamically.
The changed values should be fed into the client without the need for restarting the application.
This requirement is particularly important for micro services running in a cloud environment.
The MicroProfile Config approach allows to pick up configured values immediately after they got changed.

== Implementaions

There are a number of Config supporting projects, such as:

* Netflix Archaius (https://github.com/Netflix/archaius)
* DeltaSpike Config (http://deltaspike.apache.org/documentation/configuration.html)
* Extracted parts of DeltaSpike Config (https://github.com/struberg/javaConfig/)
* Apache Tamaya (http://tamaya.incubator.apache.org/)

== Design

A `Config` consists of the information collected from the registered `ConfigSource` instances.
These ConfigSources get sorted according to their _ordinal_.
That way it is possible to overwrite configuration with higher importance from outside.

The current configuration of an application can be accessed via `ConfigProvider#getConfig()`.

A `Config` consists of the information collected from the registered `org.eclipse.microprofile.config.spi.ConfigSource` s.
These `ConfigSource` s get sorted according to their _ordinal_.
That way it is possible to overwrite configuration with lower importance from outside.

By default there are 3 default ConfigSources:

* `System.getProperties()` (ordinal=400)
* `System.getenv()` (ordinal=300)
* all `META-INF/microprofile-config.properties` files on the ClassPath.
(default ordinal=100, separately configurable via a config_ordinal property inside each file)

Therefore, the default values can be specified in the above files packaged with the application and the value can be overwritten later for each deployment.

== Custom ConfigSources

It is possible to write and register a custom `ConfigSources`.
An example would be a ConfigSource which gets the configured values from a shared database table in a cluster.

== Building

The whole MicroProfile config project can be built via Apache Maven

`$> mvn clean install`

