//////////////////////////////////////////////////////////////////
// Copyright (c) 2016-2017 Contributors to the Eclipse Foundation 
//
// See the NOTICES file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// All rights reserved. This program and the accompanying materials 
// are made available under the terms of the Apache License, Version 2.0
// which accompanies this distribution and is available at
// http://www.opensource.org/licenses/apache2.0.php
//
// SPDX-License-Identifier: Apache-2.0
//
//////////////////////////////////////////////////////////////////

= Running the Microprofile Config TCK

Any Microprofile 1.1 and higher release must pass this test suite.
The TCK uses `testng`

== Dependencies

To enable the tests in your project you need to add the following dependency to your build:

[source, xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.apis</groupId>
    <artifactId>microprofile-config_1.0_api</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>

<dependency>
    <groupId>org.eclipse.microprofile.config.tck</groupId>
    <artifactId>microprofile-config-tck</artifactId>
    <version>1.0-SNAPSHOT</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.9.9</version>
    <scope>test</scope>
</dependency>
----

== Declaring the Tests to run

You also need to specify which tests you want to run, e.g. create a file `tck-suite.xml` in your project which contains the following content:
[source, xml]
----
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="microprofile-config-TCK" verbose="2" configfailurepolicy="continue" >

    <test name="microprofile-config 1.0 TCK">
        <packages>
            <package name="org.eclipse.microprofile.config.tck.*">
            </package>
        </packages>
    </test>

</suite>
----

== Configuration in Apache Maven pom.xml

If you use Apache Maven then the tests are run via the `maven-surefire-plugin`
[source, xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.19.1</version>
            <configuration>
                <suiteXmlFiles>
                    <suiteXmlFile>tck-suite.xml</suiteXmlFile>
                </suiteXmlFiles>
            </configuration>
        </plugin>
    </plugins>
</build>
----

== Deploying additional Implementation Artifacts

If your implementation needs additional Artifacts in the test Deployments then you have to add them via an Arquillian Extension as shown here:

https://github.com/struberg/javaConfig/blob/master/impl/src/test/java/org/apache/geronimo/config/test/GeronimoConfigExtension.java
https://github.com/struberg/javaConfig/blob/master/impl/src/test/java/org/apache/geronimo/config/test/GeronimoConfigArchiveProcessor.java
https://github.com/struberg/javaConfig/blob/master/impl/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension